server:
  port: 8089 
  
spring:
  application:
    name: CONFIG-SERVER
  
  
  cloud:
    config:
      server:
        git:
         uri: https://github.com/Dhiraj476/microservice-tutorial-config
         clone-on-start: true
         
         
         
          
  